//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContosoUniversity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Livre
    {
        public int id_livre { get; set; }
        public string titre { get; set; }
        public string langue { get; set; }
        public Nullable<int> nbre_page { get; set; }
        public string image_livre { get; set; }
        public Nullable<System.DateTime> date_parution { get; set; }
        public Nullable<int> id_auteur { get; set; }
        public Nullable<int> id_genre { get; set; }
        public Nullable<int> id_courant { get; set; }
    
        public virtual Auteur Auteur { get; set; }
        public virtual Courant Courant { get; set; }
        public virtual Genre Genre { get; set; }
    }
}
